[target.'cfg(all(target_arch = "arm", target_os = "none"))']
linker = "flip-link"
runner = "picotool load -u -v -x -t elf"
# runner = [
#   "probe-rs",
#   "run",
#   "--chip",
#   "RP235x",
#   "--log-format",
#   "[{L} at {t}s] {s:severity:bold}   {from {F}:{l}%dimmed%italic}",
# ]

[build]
target = "thumbv8m.main-none-eabihf"

[env]
# DEFMT_LOG = "trace"
# DEFMT_LOG = "debug"
DEFMT_LOG = "info"
RUST_BACKTRACE = "1"
RUSTFLAGS = "-Zmacro-backtrace"

[unstable]
build-std = ["core"]
# build-std-features = ["panic_immediate_abort"]
